%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicMixed
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicMixed').
-ic_compiled("4_3_5").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicMixed:1.0",
                   "HeuristicMixed",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicMixed:1.0".

%% returns name
name() -> "CosTransactions_HeuristicMixed".



