%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ProxyNotFound
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ProxyNotFound').
-ic_compiled("4_3_5").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ProxyNotFound:1.0",
                   "ProxyNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ProxyNotFound:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ProxyNotFound".



