%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_CallbackNotFound
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_CallbackNotFound').
-ic_compiled("4_3_5").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0",
                   "CallbackNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/CallbackNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_CallbackNotFound".



