%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_NotEmpty
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_NotEmpty').
-ic_compiled("4_3_5").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",
                   "NotEmpty",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0".

%% returns name
name() -> "CosNaming_NamingContext_NotEmpty".



