%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cos_naming_ext
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COS_NAMING_EXT_HRL).
-define(OE_COS_NAMING_EXT_HRL, true).




-endif.


