%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPushConsumer
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPUSHCONSUMER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPUSHCONSUMER_HRL, true).




-endif.


