%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushConsumer
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHCONSUMER_HRL).
-define(COSEVENTCOMM_PUSHCONSUMER_HRL, true).




-endif.


