%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTime_TimeUnavailable
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTime_TimeUnavailable').
-ic_compiled("4_3_5").


-include("CosTime.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTime/TimeUnavailable:1.0",
                   "TimeUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTime/TimeUnavailable:1.0".

%% returns name
name() -> "CosTime_TimeUnavailable".



