%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTimerEvent_TimerEventT
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTimerEvent_TimerEventT').
-ic_compiled("4_3_5").


-include("CosTimerEvent.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_struct,"IDL:omg.org/CosTimerEvent/TimerEventT:1.0","TimerEventT",
                   [{"utc",
                     {tk_struct,"IDL:omg.org/TimeBase/UtcT:1.0","UtcT",
                                [{"time",tk_ulonglong},
                                 {"inacclo",tk_ulong},
                                 {"inacchi",tk_ushort},
                                 {"tdf",tk_short}]}},
                    {"event_data",tk_any}]}.

%% returns id
id() -> "IDL:omg.org/CosTimerEvent/TimerEventT:1.0".

%% returns name
name() -> "CosTimerEvent_TimerEventT".



