%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule_StackFactory
%% Source: /net/isildur/ldisk/daily_build/17_prebuild_master-opu_o.2014-04-07_20/otp_src_17/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_STACKFACTORY_HRL).
-define(STACKMODULE_STACKFACTORY_HRL, true).




-endif.


